import random
from heap import FiboHeap




# ** correctness test generated by Gemini **




def run_tough_fibonacci_tests():
    print("==================================================")
    print("🔥 STARTING TOUGH FIBONACCI HEAP STRESS TEST 🔥")
    print("==================================================")

    # Initialize Heap
    heap = FiboHeap()
    
    # Dictionary to store node references: value -> node_object
    # We need this to perform decrease_key later
    node_refs = {}
    
    # Tracks the ground truth of what values are currently in the heap
    ground_truth_values = []

    # ---------------------------------------------------------
    # PHASE 1: Mass Insertion
    # ---------------------------------------------------------
    # We insert 50 integers in a random order. 
    # Randomness ensures the heap isn't just a single long linked list 
    # initially and tests the pointer logic thoroughly.
    print("\n[Phase 1] Inserting 50 nodes (Values 0-49)...")
    
    values_to_insert = list(range(50))
    random.shuffle(values_to_insert)
    
    for v in values_to_insert:
        node = heap.insert(v, f"Data-{v}")
        node_refs[v] = node
        ground_truth_values.append(v)
        
    print(f"✓ Inserted {len(ground_truth_values)} nodes.")
    print(f"✓ Current Min (Peeking): {heap.min_node.key}")
    
    assert heap.min_node.key == 0, f"Error: Min should be 0, got {heap.min_node.key}"

    # ---------------------------------------------------------
    # PHASE 2: Consolidation Stress
    # ---------------------------------------------------------
    # We pop the minimum ONE time. 
    # In a Fibonacci heap, this triggers the 'consolidate' phase.
    # With 50 nodes, this forces the creation of a tree structure 
    # with likely degrees up to 5 or 6 (e.g., trees of size 1, 2, 4, 8, 16, 32...).
    print("\n[Phase 2] Popping min to force tree consolidation...")
    
    popped = heap.pop() # REMEMBER: You must have renamed extract_min to pop!
    
    assert popped.key == 0, f"Error: Popped {popped.key}, expected 0"
    ground_truth_values.remove(0)
    del node_refs[0]
    
    print("✓ Consolidation complete (Internal tree structure created).")

    # ---------------------------------------------------------
    # PHASE 3: Decrease Key & Cascading Cut Stress
    # ---------------------------------------------------------
    # We will pick 15 random nodes remaining in the heap and drastically 
    # decrease their keys to negative values.
    # Because the heap was just consolidated, many of these nodes are likely 
    # children of other nodes. This forces 'Cut' and 'Cascading Cut'.
    print("\n[Phase 3] Performing 15 aggressive decrease_key operations...")
    
    # Pick 15 random values currently in the heap
    targets = random.sample(ground_truth_values, 15)
    
    for i, target_val in enumerate(targets):
        node = node_refs[target_val]
        new_key = -1 * (i + 1) # New keys: -1, -2, -3 ... -15
        
        # Update our ground truth list
        ground_truth_values.remove(target_val)
        ground_truth_values.append(new_key)
        
        # Update the reference map so we don't lose track (optional for logic, good for debug)
        del node_refs[target_val]
        node_refs[new_key] = node
        
        # PERFROM DECREASE KEY
        heap.decrease_key(node, new_key)

    print("✓ Decrease keys complete.")
    print(f"✓ New expected minimum is: {min(ground_truth_values)}")
    print(f"✓ Actual heap minimum is:  {heap.min_node.key}")
    
    assert heap.min_node.key == min(ground_truth_values), \
        f"Error: Heap min {heap.min_node.key} != Ground truth min {min(ground_truth_values)}"

    # ---------------------------------------------------------
    # PHASE 4: Total Extraction & Sorting Verification
    # ---------------------------------------------------------
    # Now we pop EVERYTHING. This verifies:
    # 1. No nodes were lost during cuts.
    # 2. The min-heap property was maintained throughout the cuts.
    # 3. The circular lists weren't broken (which would cause infinite loops).
    print("\n[Phase 4] Popping all remaining items to verify sort order...")
    
    final_extracted = []
    while heap.min_node is not None:
        node = heap.pop()
        final_extracted.append(node.key)
        
    # Sort our ground truth to compare
    ground_truth_values.sort()
    
    print(f"Extracted {len(final_extracted)} items.")
    
    if final_extracted == ground_truth_values:
        print("✓ PERFECT MATCH! The heap output is strictly sorted.")
    else:
        print("❌ FAILURE!")
        print(f"Expected: {ground_truth_values[:10]} ...")
        print(f"Got:      {final_extracted[:10]} ...")
        # Find first mismatch
        for i in range(len(ground_truth_values)):
            if i >= len(final_extracted) or final_extracted[i] != ground_truth_values[i]:
                print(f"First mismatch at index {i}: Expected {ground_truth_values[i]}, Got {final_extracted[i] if i < len(final_extracted) else 'None'}")
                break
        raise AssertionError("Heap output did not match expected sorted values.")

    print("\n==================================================")
    print("🎉 CONGRATULATIONS! YOUR FIBONACCI HEAP SURVIVED. 🎉")
    print("==================================================")


if __name__ == "__main__":
    run_tough_fibonacci_tests()